keyboards:
  ergodox_ez:
    layers:
      default:
        lights: []
        keys:
          left:
            - [esc, 1, 2, 3, 4, 5, ~]
            - [esc, q, w, e, r, t, ~]
            - [capsDance, a, s, d, f, g]
            - [lShiftDance, zDance, xDance, cDance, v, b, ~]
            - [leader, ~, ~, left, right]
          left-thumb:
            - [esc, ~]
            - [home]
            - [space, backspace, end]
          right:
            - [~, 6, 7, 8, 9, 0, ~]
            - [~, y, u, i, o, p, \]
            - [   h, j, k, l, semicolonDance, quoteDance]
            - [~, n, m, commaDance, dotDance, slashDance, rShiftDance]
            - ['[', ']', ~, ~, togglePlover]
          right-thumb:
            - [esc, ~]
            - [pageUp]
            - [pageDown, tabDance, enter]
      symbol:
        lights: [2]
        keys:
          left:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, '!', '#', '{', '}', '/', ~]
            - [~, '@', '$', '(', ')', '`']
            - [~, percentDance, circumflexDance, leftSquareBracketDance, ']', '~', ~]
            - [~, ~, ~, ~, ~]
          left-thumb:
            - [~, ~]
            - [~]
            - [~, delete, ~]
          right:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, '=', 7, 8, 9, '&', '|']
            - [   '+', 4, 5, 6, '*', ~]
            - [~, '-', 1, 2, 3, '/', ~]
            - [~, '0', '.', ~, ~]
          right-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
      navigation:
        lights: [1]
        keys:
          left:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, mouseRightButton, mouseUp, mouseLeftButton, ~, ~]
            - [~, ~, mouseLeft, mouseDown, mouseRight, ~]
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~]
          left-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
          right:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, brightnessDown, brightnessUp, ~, ~, ~]
            - [   left, down, up, right, ~, ~]
            - [~, wheelLeft, wheelDown, wheelUp, wheelRight, ~, ~]
            - [      volumeDown, volumeUp, volumeToggle, ~, ~]
          right-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
      emoji:
        lights: [1,3]
        keys:
          left:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, happyDance, sadDance, strangeDance, ~, ~]
            - [~, coolDance, okDance, loveDance, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~]
            - [enterBootloader, ~, ~, ~, ~]
          left-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
          right:
            - [~, recordMacro1, recordMacro2, stopRecordMacro, playMacro1, playMacro2, ~]
            - [~, ~, F7Dance, F8Dance, F9Dance, ~, ~]
            - [   ~, F4Dance, F5Dance, F6Dance, ~, ~]
            - [~, ~, F1Dance, F2Dance, F3Dance, ~, ~]
            - [~, ~, F10Dance, ~, ~]
          right-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
      navigation2:
        lights: [3]
        keys:
          left:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~]
          left-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
          right:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, shutdown, sleep, windowsMode, macosMode, ~, ~]
            - [   home, pageDown, pageUp, end, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, ~, ~, ~, ~]
          right-thumb:
            - [~, ~]
            - [~]
            - [~, ~, ~]
      plover:
        lights: [3]
        keys:
          left:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, sN1, sN2, sN3, sN4, sN5, ~]
            - [~, sS1, sTL, sPL, sHL, sST1]
            - [~, sS2, sKL, sWL, sRL, sST2, ~]
            - [~, ~, ~, sA, sO]
          left-thumb:
            - [~, ~]
            - [~]
            - [sA, sO, ~]
          right:
            - [~, ~, ~, ~, ~, ~, ~]
            - [~, sN6, sN7, sN8, sN9, sNA, sNB]
            - [   sST3, sFR, sPR, sLR, sTR, sDR]
            - [~, sST4, sRR, sBR, sGR, sSR, sZR]
            - [sE, sU, ~, ~, ~]
          right-thumb:
            - [~, ~]
            - [~]
            - [~, sE, sU]
    settings:
      # https://docs.qmk.fm/#/config_options?id=the-configh-file
      config: &config
        COMBO_COUNT: 6
        COMBO_TERM: 130
        ENCODER_RESOLUTION: 4
        FORCE_NKRO: ''
        LEADER_TIMEOUT: 300
        MOUSEKEY_DELAY: 0
        MOUSEKEY_INTERVAL: 20
        MOUSEKEY_MAX_SPEED: 11
        MOUSEKEY_TIME_TO_MAX: 60
        MOUSEKEY_WHEEL_DELAY: 0
        MOUSEKEY_WHEEL_MAX_SPEED: 4
        MOUSEKEY_WHEEL_TIME_TO_MAX: 150
        TAPPING_TERM: 110
        TAPPING_TERM_TAP_DANCE: 270
        UNICODE_SELECTED_MODES: 'UC_OSX, UC_WINC'

      # https://docs.qmk.fm/#/config_options?id=the-rulesmk-file
      rules: &rules
        AUDIO_ENABLE: 'no'
        BOOTMAGIC_ENABLE: 'no'
        COMBO_ENABLE: 'yes'
        COMMAND_ENABLE: 'no'
        EXTRAKEY_ENABLE: 'yes'
        NKRO_ENABLE: 'yes'
        KEY_LOCK_ENABLE: 'no'
        LEADER_ENABLE: 'yes'
        LINK_TIME_OPTIMIZATION_ENABLE: 'yes'
        RGBLIGHT_ENABLE: 'no'
        STENO_ENABLE: 'yes'
        TAP_DANCE_ENABLE: 'yes'
        UNICODE_ENABLE: 'no'
        UNICODEMAP_ENABLE: 'yes'
    combos: &combos
      - combo: [f, g]
        result: ["=", ">"]
      - combo: [y, u]
        result: [esc]
      - combo: [h, j]
        result: ["-", ">"]
      - combo: [n, m]
        result: ["_"]
      - combo: [i, o]
        result: [closeApp]
  planck:
    settings:
      rules:
        <<: *rules
        AUDIO_ENABLE: 'yes'
      config:
        <<: *config
        STARTUP_SONG: SONG(NO_SOUND)
    combos: *combos
    layers:
      default:
        lights: []
        keys:
            - [esc, q, w, e, r, t, y, u, i, o, p, \]
            - [capsDance, a, s, d, f, g, h, j, k, l, semicolonDance, quoteDance]
            - [lShiftDance, zDance, xDance, cDance, v, b, n, m, commaDance, dotDance, slashDance, rShiftDance]
            - [leader, ~, ~, delete, backspace, space, ~, tabDance, enter, '[', ']', togglePlover]
      symbol:
        lights: [1]
        keys:
            - [~, '!', '#', '{', '}','/', '=', 7, 8, 9, '&', '|']
            - [~, '@', '$', '(', ')', '`', '+', 4, 5, 6, '*', ~]
            - [~, percentDance, circumflexDance, leftSquareBracketDance, ']', '~', '-', 1, 2, 3, '/', ~]
            - [~, ~, ~, ~, ~, ~, ~, ~, 0, '.', ~, ~]
      navigation:
        lights: [2]
        keys:
            - [~, ~, mouseRightButton, mouseUp, mouseLeftButton, ~, ~, brightnessDown, brightnessUp, ~, ~, ~]
            - [~, ~, mouseLeft, mouseDown, mouseRight, ~, left, down, up, right, ~, ~]
            - [~, ~, ~, ~, ~, ~, wheelLeft, wheelDown, wheelUp, wheelRight, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~, volumeDown, volumeUp, volumeToggle, ~, ~]
      navigation2:
        lights: [2]
        keys:
            - [~, ~, ~, ~, ~, ~, shutdown, sleep, windowsMode, macosMode, ~, ~]
            - [~, audioClickToggle, audioClickUp, audioClickDown, ~, ~, home, pageUp, pageDown, end, ~, ~]
            - [~, musicToggle, musicMode, ~, ~, ~, ~, rgbBriDown, rgbBriUp, rgbSatDown, rgbSatUp, ~]
            - [~, ~, ~, ~, ~, ~, ~, rgbHueDown, rgbHueUp, rgbToggle, rgbNext, ~]
      emoji:
        lights: [1,2]
        keys:
            - [~, happyDance, sadDance, strangeDance, ~, ~, ~, F7Dance, F8Dance, F9Dance, ~, ~]
            - [~, coolDance, okDance, loveDance, ~, ~, ~, F4Dance, F5Dance, F6Dance, ~, ~]
            - [~, ~, ~, ~, ~, ~, ~, F1Dance, F2Dance, F3Dance, ~, ~]
            - [enterBootloader, ~, ~, ~, ~, ~, ~, ~, F10Dance, ~, ~, ~] 
      plover:
        lights: [2]
        keys:
            - [~, sN1, sN2, sN3, sN4, sN5, sN6, sN7, sN8, sN9, sNA, sNB]
            - [~, sS1, sTL, sPL, sHL, sST1, sST3, sFR, sPR, sLR, sTR, sDR]
            - [~, sS2, sKL, sWL, sRL, sST2, sST4, sRR, sBR, sGR, sSR, sZR]
            - [~, ~, ~, sA, sO, ~, ~, sE, sU, ~, ~, ~]

keys:
  tabDance:
    tap:
    - [tab]
    hold:
    - [holdSymbol]
  capsDance:
    tap:
    - [capsLock]
    - [toggleSymbol]
    hold:
    - [holdSymbol]
    - [holdSymbol, lCtrl]
    - [holdSymbol, lAlt]
  lShiftDance:
    tap:
    - [lShift, 9] # (
    - [lShift, '['] # {
    - ['[']
    hold:
    - [lShift]
    - [lShift, lAlt]
    - [lShift, lAlt, lgui]
  rShiftDance:
    tap:
    - [lShift, 0] # )
    - [lShift, ']'] # }
    - [']']
    hold:
    - [rShift]
    - [rShift, rAlt]
    - [rShift, rAlt, rgui]
  zDance:
    tap: [[z]]
    hold: &lCtrlDance
    - [lCtrl]
    - [lCtrl, lShift]
    - [lCtrl, lShift, lAlt]
  xDance:
    tap: [[x]]
    hold: &lAltDance
    - [lAlt]
    - [lAlt, lShift]
    - [lAlt, lShift, lCtrl]
  cDance:
    tap: [[c]]
    hold: &lGuiDance
    - [lgui]
    - [lgui, lShift]
    - [lgui, lShift, lCtrl]
  percentDance:
    tap: [['lShift', 5]] # %
    hold: *lCtrlDance
  circumflexDance:
    tap: [['lShift', 6]] # ^
    hold: *lAltDance
  leftSquareBracketDance:
    tap: [['[']]
    hold: *lGuiDance
  slashDance:
    tap: [['/']]
    hold:
    - [rCtrl]
    - [rCtrl, rShift]
    - [rCtrl, rShift, rAlt]
  dotDance:
    tap: [['.']]
    hold:
    - [rAlt]
    - [rAlt, rShift]
    - [rAlt, rShift, rCtrl]
  commaDance:
    tap: [[',']]
    hold:
    - [rgui]
    - [rgui, rShift]
    - [rgui, rShift, rCtrl]
  happyDance: {tap: [[ðŸ˜Š], [ðŸ˜], [ðŸ˜„], [ðŸ˜‚]]}
  sadDance: {tap: [[ðŸ˜ž], [ðŸ˜¢], [ðŸ˜­]]}
  coolDance: {tap: [[ðŸ˜], [ðŸ˜Ž], [ðŸ’ª], [ðŸ”¥]]}
  loveDance: {tap: [[ðŸ˜š], [ðŸ˜], [ðŸ˜˜], [ðŸ’–]]}
  strangeDance: {tap: [[ðŸ¤”], [ðŸ¤¨], [ðŸ˜±]]}
  okDance: {tap: [[ðŸ‘], [ðŸ‘Œ], [ðŸ†—]]}
  F1Dance: {tap: [['f1'], ['f11']]}
  F2Dance: {tap: [['f2'], ['f12']]}
  F3Dance: {tap: [['f3'], ['f13']]}
  F4Dance: {tap: [['f4'], ['f14']]}
  F5Dance: {tap: [['f5'], ['f15']]}
  F6Dance: {tap: [['f6'], ['f16']]}
  F7Dance: {tap: [['f7'], ['f17']]}
  F8Dance: {tap: [['f8'], ['f18']]}
  F9Dance: {tap: [['f9'], ['f19']]}
  F10Dance: {tap: [['f10'], ['f20']]}
  semicolonDance:
    tap: [[';']]
    hold:
    - [holdNavigation]
    - [holdNavigation,holdNavigation2]
  quoteDance:
    tap: [["'"]]
    hold:
    - [holdEmoji]
    - [holdEmoji, lCtrl]
    - [holdEmoji, lCtrl, lAlt]
map:
  keys:
    "'": QUOT
    '!': EXLM
    '#': HASH
    '$': DLR
    '%': PERC
    '&': AMPR
    '(': LPRN
    ')': RPRN
    '*': PAST
    '+': PPLS
    ',': COMM
    '-': MINS
    ';': SCOLON
    '=': EQL
    '@': AT
    '[': LBRC 
    '\': BSLS
    ']': RBRC 
    '^': CIRC
    '`': GRV
    'shift(': LSPO
    'shift)': RSPC
    '{': LCBR
    '|': PIPE
    '}': RCBR
    '~': TILD
    .: DOT
    /: SLSH
    backspace: BSPC
    brightnessDown: BRID
    brightnessUp: BRIU
    down: DOWN
    enter: ENT
    enterBootloader: ZKC_BTL
    left: LEFT
    leader: LEAD
    macosMode: UC_M_OS
    mouseDown: MS_D
    mouseLeft: MS_L
    mouseLeftButton: BTN1
    mouseRight: MS_R
    mouseRightButton: BTN2
    mouseUp: MS_U
    pageDown: PGDN
    pageUp: PGUP
    playMacro1: DYN_MACRO_PLAY1
    playMacro2: DYN_MACRO_PLAY2
    recordMacro1: DYN_REC_START1
    recordMacro2: DYN_REC_START2
    rgbBriDown: RGB_VAD
    rgbBriUp: RGB_VAI
    rgbHueDown: RGB_HUD
    rgbHueUp: RGB_HUI
    rgbNext: RGB_MOD
    rgbSatDown: RGB_SAD
    rgbSatUp: RGB_SAI
    rgbToggle: RGB_TOG
    right: RGHT
    sA: STN_A
    sBR: STN_BR
    sDR: STN_DR
    sE: STN_E
    sFR: STN_FR
    sGR: STN_GR
    sHL: STN_HL
    shutdown: SYSTEM_POWER
    sKL: STN_KL
    sleep: SYSTEM_SLEEP
    sLR: STN_LR
    sN1: STN_N1
    sN2: STN_N2
    sN3: STN_N3
    sN4: STN_N4
    sN5: STN_N5
    sN6: STN_N6
    sN7: STN_N7
    sN8: STN_N8
    sN9: STN_N9
    sNA: STN_NA
    sNB: STN_NB
    sO: STN_O
    space: SPC
    sPL: STN_PL
    sPR: STN_PR
    sRL: STN_RL
    sRR: STN_RR
    sS1: STN_S1
    sS2: STN_S2
    sSR: STN_SR
    sST1: STN_ST1
    sST2: STN_ST2
    sST3: STN_ST3
    sST4: STN_ST4
    sTL: STN_TL
    stopRecordMacro: DYN_REC_STOP
    sTR: STN_TR
    sU: STN_U
    sWL: STN_WL
    sZR: STN_ZR
    up: UP
    volumeDown: VOLD
    volumeToggle: MUTE
    volumeUp: VOLU
    wheelDown: WH_D
    wheelLeft: WH_L
    wheelRight: WH_R
    wheelUp: WH_U
    windowsMode: UC_M_WC
    audioClickToggle: CK_TOGG
    audioClickUp: CK_UP
    audioClickDown: CK_DOWN
    musicToggle: MU_TOG
    musicMode: MU_MOD
  prefixes:
    - AU
    - CK
    - DYN
    - MAGIC
    - MU
    - RGB
    - STN
    - UC
    - ZKC